#!/usr/bin/env bash
#this is a script is displaying "Best School" 10 times
name="Best School"
counter=1
while [ $counter -le 10 ]
do
    if [ "$counter" -eq 9 ]
    then
        echo "$name"
        echo "Hi"
    else
        echo "$name"
    fi
    ((counter++))
done
