#!/bin/bash

# Stop the currently running Nginx process
service nginx stop

# Edit the Nginx configuration file to run Nginx as the nginx user
sed -i 's/user  nginx;/user  nginx nginx;/g' /etc/nginx/nginx.conf

# Start Nginx as the nginx user and listen on all active IPs on port 8080
nginx -g "daemon off;"
