#!/usr/bin/env bash
# # Edit the Nginx configuration file to run Nginx as the nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
# replace all instances of "80" with "8080" in the file
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
# change the file permissions
chmod 644 /etc/nginx/nginx.conf
# will terminate all running instances of the Apache
pkill apache2
# start the Nginx service as the "nginx" user
sudo -u nginx service nginx start
