#!/usr/bin/env bash
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
# here a bash script that configures the container to run Nginx as the nginx user and listen on all active IPs on port 8080
